# Generated by Django 5.2.3 on 2025-06-14 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_rename_cards_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts.folder'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts.folder'),
        ),
    ]
